### ISSUE TITLE
Wrong auto renew date

### ISSUE THREAD

**Issue by tannerm** [restrictcontentpro/restrict-content-pro#293]
When a user cancels an auto renew subscription then switches to another auto renew subscription, the new renewal date is incorrect when compared with Stripes renewal date.

To recreate, register for a subscription with auto renew checked. Then cancel the subscription and upgrade to a new one. Once the new subscription receives a pingback from Stripe you'll notice that the renewal date from RCP is different from the renewal date in Stripe.

Here's a screencast:
https://www.dropbox.com/s/nb2m26et9sh1stm/issue.mp4?dl=0

**Comment by tannerm** [comment]
@pippinsplugins This seems like a pretty big deal and want to make sure you see it.

**Comment by swb1192** [comment]
When this renewal goes through, it looks like it is doing a duplicate of the renewal, as per the User Notes in the member data:

November 22, 2015 18:23:19 - Member's expiration changed from 2016-11-22 23:59:59 to 2017-11-22 23:59:59

November 22, 2015 18:23:19 - Member's expiration changed from 2017-11-22 23:59:59 to 2018-11-22 23:59:59

**Comment by pippinsplugins** [comment]
I'll dig into this as soon as I can.

**Comment by pippinsplugins** [comment]
@tannerm How much are the dates off by?

**Comment by tannerm** [comment]
@pippinsplugins normally by a year or two. (I'm assuming that would change to whatever unit is used for the subscription).

**Comment by swb1192** [comment]
The renewals should be 1 year, but instead they are two years (see https://github.com/pippinsplugins/restrict-content-pro/issues/293#issuecomment-159436317).

**Comment by pippinsplugins** [comment]
Pretty sure I've tracked this down.

**Comment by pippinsplugins** [comment]
@tannerm Could you test it against the PR above? I'm pretty sure that resolves it.

**Comment by pippinsplugins** [comment]
#303 should resolve this.

**Comment by tannerm** [comment]
Sorry for the delay here, @pippinsplugins. I just pulled down the master branch and tested again and am still seeing the same results. Happy to do a screenshare if that would help.

**Comment by tannerm** [comment]
Or if you wait long enough, I'll have time to dig into this myself. :P

**Comment by pippinsplugins** [comment]
Ok I'm struggling to find what's causing this because I cannot replicate it at all.

Any ideas from anyone here?

**Comment by tannerm** [comment]
Yeah, I'll look into this. I should have some time over the next couple of days.

**Comment by pippinsplugins** [comment]
Here's an example of a subscriber on one of my live sites who has renewed three times recently. Everytime the expiration date was properly calculated:

```
October 22, 2015 14:16:30 - Member's expiration changed from 2015-10-22 23:59:59 to 2015-11-22 23:59:59

November 22, 2015 13:14:59 - Member's expiration changed from 2015-11-22 23:59:59 to 2015-12-22 23:59:59

December 22, 2015 13:17:19 - Member's expiration changed from 2015-12-22 23:59:59 to 2016-01-22 23:59:59
```

**Comment by pippinsplugins** [comment]
I've tracked this down I believe. Should be resolved with changes done for #312.

@tannerm @swb1192 if you see new instances after 2.4.6 is released, please re-open.

**Comment by pippinsplugins** [comment]
Correction: 2.4.7

**Comment by tannerm** [comment]
Hey @pippinsplugins!

I updated to 2.4.7 and I'm still seeing the issue. I'll take some time this week to see if I can track it down.

**Comment by pippinsplugins** [comment]
Ugh. I've worked with 5-10 customers in the last two weeks that had the same issue and it has been resolved for all of them.

**Comment by pippinsplugins** [comment]
Ok guys, I'm pretty sure I've finally tracked this down and resolved it. @tannerm Any chance you could test it?

**Comment by pippinsplugins** [comment]
Just did some more testing, found some issues, but not it's all working exactly as expected.
